server.port=8080
spring.application.name=vintushtech-sales-microservice

# Reactive Logging
logging.level.com.vintushtech=INFO
logging.level.org.springframework.web.reactive=INFO

# FastAPI Target for Reactive WebClient
fastapi.service.url=http://localhost:8000
