server.port=8080
spring.application.name=apexsales-microservice

# Reactive Logging
logging.level.com.apexsales=INFO
logging.level.org.springframework.web.reactive=INFO

# FastAPI Target for Reactive WebClient
fastapi.service.url=http://localhost:8000
